play:
  build: .
  links:
    - db
  ports:
    - "9003:9000"
  volumes:
    - ~/.ivy2:/root/.ivy2
    - ~/.sbt:/root/.sbt
db:
  image: mariadb:10
  environment:
    MYSQL_DATABASE: myfleet
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
